import type { Metadata } from "next";
import "./globals.css";
//import { Providers } from "./dashboard/components/Provisders";
import { AuthProvider } from "@/Context/AuthProvider" 
import { OrderProvider } from "@/Context/order-context";
import { Toaster } from "@/components/ui/toaster"
import { PlansProvider } from "@/Context/plans-context"

export const metadata: Metadata = {
  title: "Duria",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <AuthProvider>          {/* ← ENVOLVER TUDO */}
          <PlansProvider>
            <OrderProvider>
              {children}
              <Toaster />
            </OrderProvider>
          </PlansProvider>
        </AuthProvider>
        </body>
    </html>
  );
}
