import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./dashboard/components/Provisders";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br"> 
      <body suppressHydrationWarning ><Providers>{children}</Providers></body>
    </html>
  );
}
